import type { Metadata } from "next";
import { Poppins, Antonio } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Testimonials from "@/components/Testimonials";
import Footer from "@/components/Footer";
import LayoutExtras from "@/components/LayoutExtras";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-poppins",
});


const antonio = Antonio({
  variable: "--font-antonio",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins.variable} ${antonio.variable} antialiased`}
      >
        <Navbar />
        {children}
        <LayoutExtras />
        <Testimonials />
        <Footer />
      </body>
    </html>
  );
}
